# ----
# Site

title: Danish Delights Bakery
url: "https://danishdelights.co.nz"
baseurl:
google_analytics_key:
google_maps_javascript_api_key: AIzaSyC6osa-Gws5vIqoHiQnGnduGTqU-DSdQJY
timezone: Etc/UTC

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Danish Delights, a Dunedin bakery
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Danish Delights Bakery

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
